version: "3.1"

services:
  mongo-grid:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: toor

  mongo-express:
    image: mongo-express
    restart: always
    links:
      - mongo-grid:mongo
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: toor
